### ISSUE TITLE
Any provision for secure coding?

### ISSUE THREAD

**Issue by RaoShri** [rsd-devel/rsd#34]
Hi,
I was looking into security aspects of RISCV processors. Is there any provision for making a block of memory secure in rsd? Like TZPC for ARM?
Regards,
Shrinidhi

**Comment by shioyadan** [comment]
Hi RaoShri,

I missed this issue and I'm sorry for the late reply.
RSD has a very simple static address translation and memory protection mechanism, but it does not have a more advanced security mechanism. We would like to prioritize the implementation of memory protection by the regular MMU first.
