### ISSUE TITLE
Wiki issue

### ISSUE THREAD

**Issue by a-kest** [rsd-devel/rsd#71]
In the Wiki under "en arch microarch" there is a link to refer too:

[An Open Source FPGA-Optimized Out-of-Order RISC-V Soft Processor](http://sv.rsg.ci.i.u-tokyo.ac.jp/pdfs/Mashimo-FPT'19.pdf)

However this link does not work.

**Comment by a-kest** [comment]
I believe this is the new correct link:

https://www.rsg.ci.i.u-tokyo.ac.jp/members/shioya/pdfs/Mashimo-FPT%2719.pdf

**Comment by shioyadan** [comment]
Thank you for your suggestion.
I updated the link.
