### ISSUE TITLE
[Bug Report] RSD doesn't update mstatus after `mret` instruction

### ISSUE THREAD

**Issue by zhangkanqi** [rsd-devel/rsd#76]
**Bug Description:**

The previous value of `mstatus` is 0x00007800, but after executing `mret` instruction, `mstatus` is still 0x00007800.
However, according to the riscv specification as below, `mstatus` should be 0x80006080, which spike does so.

![image](https://github.com/rsd-devel/rsd/assets/34207592/f2181aa6-4181-4676-a998-a208dda1a3f2)

**Comment by shioyadan** [comment]
Thank you for your report. After checking the specification, I found the following statement, which leads me to believe that the FS field should be updated by privileged code (software), and the SD should be updated by hardware according to the FS. Consequently, it appears that the hardware does not need to update the FS on the mret. Furthermore, the FS and SD have not been implemented yet and should be implemented.

![image](https://github.com/rsd-devel/rsd/assets/6016305/766198b8-dbb5-4e66-b5c1-9218951fba07)
