### ISSUE TITLE
[Bug Report]  `fflags.DZ` set incorrectly after  `fdiv.s` instruction

### ISSUE THREAD

**Issue by zhangkanqi** [rsd-devel/rsd#91]
**Environment:**

 RSD version: bd7c5c12dfd8d20c7cb5c1d5a75f7ba59f9fce52
  
<br/>

**Bug Description:**

There is an instruction `fdiv.s  fs1, fa4, ft7`, where `fa4=0x47bca361` and `ft7=0x00000000`.

After the `fdiv.s` instruction, `fflags.DZ` flag in RSD maintains 0 . However, `fflags.DZ`  flag  in spike is set to 1 .

<br/>

It seems that RSD update `fflags.DZ` incorrectly.

**Comment by lpha-z** [comment]
From what I can see, it does not appear to be implemented, but I don't know how it actually is. @ RSD team?
